In [2]:
import numpy as np
d=np.arange(10)
c=np.arange(3)
d


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
c=range(3)
c

range(0, 3)

In [6]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
c=np.arange(15).reshape(3,4)
c

ValueError: ignored

In [9]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
print(a.ndim)
print(a.size)

2
15


In [11]:
print(a.shape)

(3, 5)


In [12]:
print(a.dtype)

int64


In [13]:
print(d.itemsize)

8


In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [15]:
help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [16]:
b=np.array([5.,6.,7.,8.])
print(b)
print(b.dtype)
print(type(b))

[5. 6. 7. 8.]
float64
<class 'numpy.ndarray'>


In [19]:
c=np.eye(10)
dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
c=np.eye(10)
#dtype=np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
d=np.linspace(-1,2,15,endpoint=True)
d

array([-1.        , -0.78571429, -0.57142857, -0.35714286, -0.14285714,
        0.07142857,  0.28571429,  0.5       ,  0.71428571,  0.92857143,
        1.14285714,  1.35714286,  1.57142857,  1.78571429,  2.        ])

In [25]:
e=np.logspace(-1,2,15,endpoint=True,base=10)
e

array([  0.1       ,   0.16378937,   0.26826958,   0.43939706,
         0.71968567,   1.17876863,   1.93069773,   3.16227766,
         5.17947468,   8.48342898,  13.89495494,  22.75845926,
        37.2759372 ,  61.05402297, 100.        ])

In [27]:
p=np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)
p

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a*2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [30]:
a+a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [31]:
a*a


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [32]:
b=a.transpose()
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [33]:
a@b

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [34]:
print(a)
a.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [35]:
a.sum()

66

In [36]:
print(a.max())

11


In [37]:
print(a.min())

0


In [39]:
b=a*np.pi/1
b

array([[ 0.        ,  3.14159265,  6.28318531,  9.42477796],
       [12.56637061, 15.70796327, 18.84955592, 21.99114858],
       [25.13274123, 28.27433388, 31.41592654, 34.55751919]])

In [40]:
c=np.sin(b)
c

array([[ 0.00000000e+00,  1.22464680e-16, -2.44929360e-16,
         3.67394040e-16],
       [-4.89858720e-16,  6.12323400e-16, -7.34788079e-16,
         8.57252759e-16],
       [-9.79717439e-16,  1.10218212e-15, -1.22464680e-15,
         4.89982516e-15]])

In [42]:
d=b+c
d

array([[ 0.        ,  3.14159265,  6.28318531,  9.42477796],
       [12.56637061, 15.70796327, 18.84955592, 21.99114858],
       [25.13274123, 28.27433388, 31.41592654, 34.55751919]])

In [44]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
a[3]


3

In [46]:
a[2:3]

array([2])

In [47]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
a[1,1]

6

In [49]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [51]:
a=a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
for reha in a:
  print(reha)
a=np.arange(15).reshape(3,5)
print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [54]:
for egg in a.flat:
  print(egg)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [55]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b=a
b is a


True

In [59]:
b.shape=(2,5)
b
a.shape

(2, 5)

In [60]:
b is a
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
a=np.arange(12)
c=a[:]
a.shape=(3,4)
a
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [62]:
c[1]=-1
a
print(e)

[  0.1          0.16378937   0.26826958   0.43939706   0.71968567
   1.17876863   1.93069773   3.16227766   5.17947468   8.48342898
  13.89495494  22.75845926  37.2759372   61.05402297 100.        ]


In [63]:
d=c[3:8]
d

array([3, 4, 5, 6, 7])

In [65]:
d[:]=0
a
print(c)
print(d)

[ 0 -1  2  0  0  0  0  0  8  9 10 11]
[0 0 0 0 0]


In [67]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [69]:
d=b.copy()
d[:,:]=0.0
a
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]]
