In [2]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a[a>5]=0
a

array([[0, 1, 2, 3],
       [4, 5, 0, 0],
       [0, 0, 0, 0]])

In [4]:
a[a==0]=-1
a

array([[-1,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

In [5]:
a==-1

array([[ True, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [8]:
a=np.arange(12).reshape(3,4)
a[np.logical_and(a>2,a<8)]=0.0
a

array([[ 0,  1,  2,  0],
       [ 0,  0,  0,  0],
       [ 8,  9, 10, 11]])

In [9]:
a>3

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [12]:
#AVOIDING LOOPS
P=32
Q=64
xmin=ymin=0.0
xmax=ymax=1.0
x=np.linspace(xmin,xmax,P,endpoint=False)
y=np.linspace(ymin,ymax,Q,endpoint=True)
print(x.shape)
y

(32,)


array([0.        , 0.01587302, 0.03174603, 0.04761905, 0.06349206,
       0.07936508, 0.0952381 , 0.11111111, 0.12698413, 0.14285714,
       0.15873016, 0.17460317, 0.19047619, 0.20634921, 0.22222222,
       0.23809524, 0.25396825, 0.26984127, 0.28571429, 0.3015873 ,
       0.31746032, 0.33333333, 0.34920635, 0.36507937, 0.38095238,
       0.3968254 , 0.41269841, 0.42857143, 0.44444444, 0.46031746,
       0.47619048, 0.49206349, 0.50793651, 0.52380952, 0.53968254,
       0.55555556, 0.57142857, 0.58730159, 0.6031746 , 0.61904762,
       0.63492063, 0.65079365, 0.66666667, 0.68253968, 0.6984127 ,
       0.71428571, 0.73015873, 0.74603175, 0.76190476, 0.77777778,
       0.79365079, 0.80952381, 0.82539683, 0.84126984, 0.85714286,
       0.87301587, 0.88888889, 0.9047619 , 0.92063492, 0.93650794,
       0.95238095, 0.96825397, 0.98412698, 1.        ])

In [13]:
import time
import numpy as np
M=32
N=64
x=np.linspace(0,1,M,endpoint=False)
y=np.linspace(0,1,N)
x

array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    , 0.53125, 0.5625 , 0.59375, 0.625  ,
       0.65625, 0.6875 , 0.71875, 0.75   , 0.78125, 0.8125 , 0.84375,
       0.875  , 0.90625, 0.9375 , 0.96875])

In [14]:
y

array([0.        , 0.01587302, 0.03174603, 0.04761905, 0.06349206,
       0.07936508, 0.0952381 , 0.11111111, 0.12698413, 0.14285714,
       0.15873016, 0.17460317, 0.19047619, 0.20634921, 0.22222222,
       0.23809524, 0.25396825, 0.26984127, 0.28571429, 0.3015873 ,
       0.31746032, 0.33333333, 0.34920635, 0.36507937, 0.38095238,
       0.3968254 , 0.41269841, 0.42857143, 0.44444444, 0.46031746,
       0.47619048, 0.49206349, 0.50793651, 0.52380952, 0.53968254,
       0.55555556, 0.57142857, 0.58730159, 0.6031746 , 0.61904762,
       0.63492063, 0.65079365, 0.66666667, 0.68253968, 0.6984127 ,
       0.71428571, 0.73015873, 0.74603175, 0.76190476, 0.77777778,
       0.79365079, 0.80952381, 0.82539683, 0.84126984, 0.85714286,
       0.87301587, 0.88888889, 0.9047619 , 0.92063492, 0.93650794,
       0.95238095, 0.96825397, 0.98412698, 1.        ])

In [19]:
t0=time.time()
g=np.zeros((M,N))
for i in range(M):
  for j in range(N):
    g[i,j]=np.sin(2*np.pi*x[i]*y[j])
t1=time.time()
print("time elapsed:{} s".format(t1-t0))    
    

time elapsed:0.006300449371337891 s


In [20]:
x2d,y2d=np.meshgrid(x,y,indexing="ij")
print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])


[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.01587302 0.03174603 0.04761905 0.06349206 0.07936508
 0.0952381  0.11111111 0.12698413 0.14285714 0.15873016 0.17460317
 0.19047619 0.20634921 0.22222222 0.23809524 0.25396825 0.26984127
 0.28571429 0.3015873  0.31746032 0.33333333 0.34920635 0.36507937
 0.38095238 0.3968254  0.41269841 0.42857143 0.44444444 0.46031746
 0.47619048 0.49206349 0.50793651 0.52380952 0.53968254 0.55555556
 0.57142857 0.58730159 0.6031746  0.61904762 0

In [27]:
hello=np.array([10,20,30,40,50,60])
print(hello)
np.concatenate([hello,hello],axis=1)

[10 20 30 40 50 60]


AxisError: ignored

In [29]:
x=[1,2,3,4,5,6,1,2,3,4,5]
x1,x2,x3,x4=np.split(x,[3,2,8])
print(x1,x2,x3,x4)

[1 2 3] [] [3 4 5 6 1 2] [3 4 5]


In [31]:
grid=np.arange(25).reshape(5,5)
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
left,right=np.hsplit(grid,[2])
print(left)
right

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]]


array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [33]:
x=np.arange(1,9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.add.reduce(x)

36

In [36]:
np.multiply.accumulate(x)

array([    1,     2,     6,    24,   120,   720,  5040, 40320])